app            = 'pong-ikvm-q'
primary_region = 'nrt'

[env]
HTTP_PORT           = '8080'
SOLID_QUEUE_IN_PUMA = 'true'
TZ                  = 'Asia/Tokyo'

[http_service]
internal_port = 8080
force_https   = true

[[http_service.checks]]
grace_period = '20s'
interval     = '10s'
timeout      = '1s'
path         = '/up'

[[vm]]
cpu_kind = 'shared'
cpus     = 1
memory   = '512mb'
