app            = 'pong-ikvm-q'
primary_region = 'nrt'

[env]
HTTP_PORT           = '8080'
SOLID_QUEUE_IN_PUMA = 'true'
TZ                  = 'Asia/Tokyo'

[http_service]
internal_port = 8080
force_https   = true

[[http_service.checks]]
grace_period = '10s'
interval     = '15s'
timeout      = '1s'
path         = '/up'

[mounts]
source      = 'storage'
destination = '/rails/storage'

[[vm]]
memory = '512mb'
