default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: pong_development

test:
  <<: *default
  database: pong_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    database: pong_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: pong_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: pong_production_cable
    migrations_paths: db/cable_migrate
