service: pong
image: ursm/pong

servers:
  web:
    - app1

proxy:
  host: pong.ursm.jp

registry:
  username: ursm

  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - LITESTREAM_REPLICA_ENDPOINT
    - RAILS_MASTER_KEY

  clear:
    LITESTREAM_IN_PUMA:  true
    SOLID_QUEUE_IN_PUMA: true
    TZ:                  Asia/Tokyo

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "pong_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  user: ursm
