service: pong
image: ursm/pong

servers:
  web:
    hosts:
      - app1: litefs1
      - app2: litefs2

    options:
      publish:
        - 20202:20202

      device:
        - /dev/fuse

      cap-add:
        - SYS_ADMIN

proxy:
  host: pong.ursm.jp
  app_port: 8080

registry:
  username: ursm

  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY

  clear:
    TZ: Asia/Tokyo

  tags:
    litefs1:
      LITEFS_ADVERTISE_URL: http://10.0.0.3:20202
      LITEFS_HOSTNAME:      app1

    litefs2:
      LITEFS_ADVERTISE_URL: http://10.0.0.4:20202
      LITEFS_HOSTNAME:      app2

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "pong_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  user: ursm

accessories:
  consul1: &consul
    image: hashicorp/consul:1.21.0
    host: bastion

    cmd: >
      agent
      -server
      -data-dir=/consul
      -client=0.0.0.0
      -node=bastion
      -advertise=10.0.0.2
      -bootstrap-expect=3
      -retry-join=10.0.0.3
      -retry-join=10.0.0.4

    volumes:
      - consul:/consul

    options:
      publish:
        - 8300-8301:8300-8301
        - 8301:8301/udp
        - 8500:8500

  consul2:
    <<: *consul
    host: app1

    cmd: >
      agent
      -server
      -data-dir=/consul
      -client=0.0.0.0
      -node=app1
      -advertise=10.0.0.3
      -bootstrap-expect=3
      -retry-join=10.0.0.2
      -retry-join=10.0.0.4

  consul3:
    <<: *consul
    host: app2

    cmd: >
      agent
      -server
      -data-dir=/consul
      -client=0.0.0.0
      -node=app2
      -advertise=10.0.0.4
      -bootstrap-expect=3
      -retry-join=10.0.0.2
      -retry-join=10.0.0.3
