access-key-id:     $LITESTREAM_ACCESS_KEY_ID
secret-access-key: $LITESTREAM_SECRET_ACCESS_KEY

dbs:
  - path: storage/production.sqlite3
    replicas:
      - type:     s3
        endpoint: $LITESTREAM_REPLICA_ENDPOINT
        bucket:   $LITESTREAM_REPLICA_BUCKET
        path:     production.sqlite3

  - path: storage/production_cache.sqlite3
    replicas:
      - type:     s3
        endpoint: $LITESTREAM_REPLICA_ENDPOINT
        bucket:   $LITESTREAM_REPLICA_BUCKET
        path:     production_cache.sqlite3

  - path: storage/production_queue.sqlite3
    replicas:
      - type:     s3
        endpoint: $LITESTREAM_REPLICA_ENDPOINT
        bucket:   $LITESTREAM_REPLICA_BUCKET
        path:     production_queue.sqlite3

  - path: storage/production_cable.sqlite3
    replicas:
      - type:     s3
        endpoint: $LITESTREAM_REPLICA_ENDPOINT
        bucket:   $LITESTREAM_REPLICA_BUCKET
        path:     production_cable.sqlite3
